version: "3.8"

services:
  mongo:
    image: mongo
    restart: always

  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    restart: unless-stopped
    environment:
      - DATABASE_URI=mongodb://mongo
      - COLLECTION=Production
      - URI_PARAMS=?retryWrites=true&w=majority
    depends_on:
      - mongo

  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
      args:
        - VITE_BACKEND_URL=/api

  nginx:
    image: nginx:1.20
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend
